### ISSUE TITLE
Get feedback about v1 UUID usage

### ISSUE THREAD

**Issue by ctavan** [bcoe/proposal-standard-library-uuid#19]
Based on the [list of most popular github repos which use v1 UUIDs](https://docs.google.com/spreadsheets/d/1NjrsNgEZaXs10tXBRGgMpA-9rh_a3rEQlKfi1TpAnYI/edit#gid=1733527776) (see #16) I would like to asses for a few of the most popular repos whether `v1` UUIDs have been chosen deliberately or whether the hypothesis that `v1` just sounds more "defaulty" than `v4` led developers to mistakenly choose `v1` UUIDs where `v4` UUIDs would have been a better choice (see https://github.com/bcoe/proposal-standard-library-uuid/issues/4#issuecomment-500823549 for initial thoughts).

My plan is to open GitHub issues on the affected repos, here's a suggestion for an issue template:

> I'm a co-author of the `uuid` module and I'm currently contributing to a proposal that seeks to promote the `uuid` module into a (yet to be defined) "JavaScript standard library".

> We are currently evaluating how the `uuid` module is being used by popular Open Source projects and found that [time-based `v1` UUIDs](https://github.com/kelektiv/node-uuid#version-1) are being used in this project. Was there a specific reason for choosing `v1` UUIDs over the simpler [purely random `v4` UUIDs](https://github.com/kelektiv/node-uuid#version-4)?

I will use the Google Sheet to take notes on whether I believe `v1` UUIDs could be replaced by `v4` in certain projects and will also use it to consolidate the feedback we'll get.

Is everyone of you fine with this approach? Would love to get some feedback on the issue template before I start posting (which may also give our standardization effort a bit more visibility).

**Comment by ctavan** [comment]
I have started to reach out to a few popular open source projects who were using `v1` UUIDs and so far I've gotten pretty positive feedback. In most cases usage of `v1` UUIDs turned out to be rather coincidental and not deliberate:

- [x] https://github.com/storybookjs/storybook/pull/7397
- [x] https://github.com/TryGhost/Ghost/pull/10871
- [x] https://github.com/gatsbyjs/gatsby/pull/15407
- [ ] https://github.com/influxdata/chronograf/pull/5235 (feedback pending)
- [ ] https://github.com/cowbell/sharedrop/pull/78 (feedback pending)

**Comment by littledan** [comment]
Based on the analysis document, it looks like this task is complete, right? Great work!

**Comment by ctavan** [comment]
Agree.

Since the purpose of this proposal is not to fix all existing `uuid` npm module usage but instead proposing a new standard library API that prevents wrong/inappropriate usage of UUIDs _in the future_ I believe we have all relevant information in https://github.com/bcoe/proposal-standard-library-uuid/blob/master/analysis/README.md now and can consider this task complete.
