### ISSUE TITLE
Investigate non-v4 UUID usage

### ISSUE THREAD

**Issue by ctavan** [bcoe/proposal-standard-library-uuid#4]
The initial discussion in #3 brought up the question whether the UUID standard module should support UUID versions other than v4 from the beginning.

A rough analysis of the [BigQuery Github dataset revealed](https://github.com/bcoe/proposal-standard-module-uuid/issues/3#issuecomment-491510271) revealed the following usage:

```
Row version cnt   ratio 
1   v4      18318 0.797
2   v1      4399  0.191
3   v5      231   0.010
4   v3      29    0.001
```

@littledan made the hypothesis that some part of `v1` UUID usage could actually be caused by developers having accidentally chosen the wrong UUID version since `v1` sounds much more like the "default" UUID type rather than `v4`.

To verify this hypothesis I suggest to look a bit deeper into the BigQuery Github dataset and:
* Extract the repos that make use of v1
* Sort them by github stars or watch count
* Pick the most prominent modules and check how and why they use v1 UUIDs
* Potentially get in touch with the maintainers of these modules to clarify why v1 is being used instead of v4

We could do the same for v3/5.

Does this make sense to you? Anything you would add or do differently? Would be great to get some feedback before I actually start working on this 🙂.

**Comment by ctavan** [comment]
The initial analysis has been performed in #16 and more in-depth investigations for v1 UUIDs will follow in #19 so I think we can just continue there.

**Comment by bcoe** [comment]
@ctavan thank you for doing this. as per @codehag's out of band feedback; perhaps a next good step, before we dig too deep into the data you've collected, is coming up with a set of hypothesis that we're trying to prove or disprove.

If we take on the qualitative approach of reaching out to a few folks using UUID v1, etc., we also need to be careful not to come in with a bias point of view.

**Comment by ctavan** [comment]
@bcoe agree.

So let's first try to characterize the 3 classes of UUIDs that are described in the RFC:

- v4 completely random, very simple algorithm, 122 random bits
- v1 time-based, complex algorithm, if not used carefully, collisions are much more likely than with v4. UUIDs are time-ordered.
- v3/5 namespace-based, special use case. constant input leads to constant output.

**Hypothesis:** Following the principle of least surprise the hypothesis is that you should always use the simplest UUID version that fulfills your use case because this reduces the risk of unexpected problems. So if all you need is a unique identifier, you should always use v4 UUIDs. Only if you need time-ordering you should use v1. And only if you need namespacing, you should use v3/5.

In particular, accidentally using v1 instead of v4 UUIDs in cases where the developer is simply expecting a random value but is not aware of the fact that the generated IDs are time-ordered can have very negative consequences:

- If these IDs are used as database keys and a database/cache does ID-based sharding, it can lead to "hot shards".
- Developers who unintentionally use v1 UUIDs in public datasets may not be aware of the fact that the creation timestamp and MAC address are leaked. See Wikipedia: [“This privacy hole was used when locating the creator of the Melissa virus.”](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_1_(date-time_and_MAC_address))

Given these assumptions we want to understand whether:
1. the various versions of UUIDs are being used according to their properties which would favor an API, that is symmetric in the UUID versions like the current uuid npm module
1. or if we should correct for accidental misuse by designing an API that favors v4 UUIDs over the other UUIDs.

Do you agree with these ideas?

**Comment by ctavan** [comment]
Non-v4 UUID usage has been analyzed in detail in https://github.com/bcoe/proposal-standard-library-uuid/blob/master/analysis/README.md

Let's close this one and wait for explicit feedback on the analysis to figure out if additional research is necessary.

**Comment by littledan** [comment]
The analysis looks great. I'm very happy to see the responsible approach taken here, including following up with the inappropriate users of UUID v1. Seems like we can conclude that the UUID standard library should only support v4.
